recipe: wordpress
config:
  php: '8.1'
  via: nginx
  webroot: .
  xdebug: false
  database: mariadb
  composer_version: '1.10.1'
services:
  database:
    creds:
      user: wordpress
      password: wordpress
      database: wordpress
name: recipepocket
